"""replace resume link with s3 fields

Revision ID: 3c1f195de1eb
Revises: bf66161280cf
Create Date: 2026-06-18 19:55:29.104154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1f195de1eb'
down_revision: Union[str, Sequence[str], None] = 'bf66161280cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('resume_s3_key', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('resume_filename', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('resume_uploaded_at', sa.DateTime(), nullable=True))
    op.drop_column('student_profiles', 'resume_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('resume_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('student_profiles', 'resume_uploaded_at')
    op.drop_column('student_profiles', 'resume_filename')
    op.drop_column('student_profiles', 'resume_s3_key')
    # ### end Alembic commands ###
